CREATE DATABASE PracticeDB;
SELECT   * FROM customer_shoping_behavior

--1. Total revenue generated by male vs female customers
select
gender,
sum(purchase_amount) as total_revenue
from customer_shoping_behavior
group by gender;

--2. Customers who used a discount but spent more than the average purchase amount
select distinct customer_id,purchase_amount
from customer_shoping_behavior
where discount_applied = 'Yes'
and purchase_amount> (select avg(purchase_amount)
from customer_shoping_behavior );

-- Top 5 products with the highest average review rating
select TOP 5 item_purchased,
avg(review_rating) as avg_review_rating
from customer_shoping_behavior
group by item_purchased
order by avg_review_rating DESC

--4. Average purchase amount by shipping type (Standard vs Express)
 SELECT shipping_type,
 avg(purchase_amount) as  avg_purchse_amount
 from customer_shoping_behavior
 group by shipping_type

 --5 Do subscribed customers spend more ?

 select subscription_status,
 avg(purchase_amount) as avg_spend,
 sum(purchase_amount) as total_revenue
 from customer_shoping_behavior
 group by subscription_status

---6. Top 5 products with the highest percentage of discounted purchases
SELECT 
 top 5  item_purchased,
    ROUND(
        SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 
        / COUNT(*), 2
    ) AS discount_percentage
FROM customer_shoping_behavior
GROUP BY item_purchased
ORDER BY discount_percentage DESC

--- 7. Customer segmentation (New, Returning, Loyal)

SELECT 
    CASE 
        WHEN previous_purchases= 0 THEN 'New'
        WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(DISTINCT customer_id) AS customer_count
FROM customer_shoping_behavior
GROUP BY 
    CASE 
        WHEN previous_purchases = 0 THEN 'New'
        WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END;

---8 Top 3 most purchased products within each category
select category, item_purchased,purchased_count
from(
select category,item_purchased,
count(*) as purchased_count,
ROW_NUMBER()over( partition by category order by count(*) desc
) as rn from customer_shoping_behavior 
group by item_purchased,category)t
where rn<=3;

--9. Are repeat buyers (more than 5 previous purchases) more likely to be subscribers?
select subscription_status,
   count(distinct customer_id) as customer_count
from customer_shoping_behavior
where previous_purchases >5
group by subscription_status;

--- 10. Revenue contribution by age group--
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer_shoping_behavior
GROUP BY age_group
ORDER BY total_revenue DESC;

